# Generated by Django 4.0 on 2021-12-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=50)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("release_date", models.DateTimeField(verbose_name="release date")),
                ("image", models.URLField()),
                ("artists", models.ManyToManyField(to="tracks.Artist")),
                ("links", models.ManyToManyField(to="tracks.Link")),
            ],
        ),
        migrations.AddField(
            model_name="artist",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracks.link"
            ),
        ),
    ]
