# Generated by Django 4.0 on 2021-12-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="link",
        ),
        migrations.AddField(
            model_name="artist",
            name="links",
            field=models.ManyToManyField(to="tracks.Link"),
        ),
    ]
