# Generated by Django 4.0 on 2021-12-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0002_remove_artist_link_artist_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=50)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=50)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="track",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="links",
        ),
        migrations.RemoveField(
            model_name="track",
            name="links",
        ),
        migrations.DeleteModel(
            name="Link",
        ),
        migrations.AddField(
            model_name="tracklink",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracks.track"
            ),
        ),
        migrations.AddField(
            model_name="artistlink",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracks.artist"
            ),
        ),
    ]
