# Generated by Django 4.0 on 2021-12-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0003_artistlink_tracklink_rename_name_track_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistlink",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link",
                to="tracks.artist",
            ),
        ),
        migrations.AlterField(
            model_name="tracklink",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link",
                to="tracks.track",
            ),
        ),
    ]
