repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        args: ['--check', '--diff', '.']
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ['--profile=black', '--lines-after-imports=2', '--check-only', '.']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: ['--max-line-length=120', '--ignore=F401']
